### ISSUE TITLE
Question regarding the pSDG sampler

### ISSUE THREAD

**Issue by ThGaskin** [alisiahkoohi/Langevin-dynamics#2]
Hi, 

in [line 105](https://github.com/alisiahkoohi/Langevin-dynamics/blob/495de3a6004c07fef1f9b1c3922451f97854736d/langevin_sampling/precondSGLD.py#L105C25-L105C25) of `precondSGLD.py`, why are you dividing by G to obtain the `noise_std`? Surely following the paper by Li et al. you should be multiplying by G? Or am I missing something? Because this line is causing my parameter estimates to explode ... 
Thanks!

**Comment by ThGaskin** [comment]
Never mind -- realised my mistake :)

**Comment by alisiahkoohi** [comment]
I understand how that can be confusing. As you already know, G is defined as the inverse of the preconditioning matrix
