### ISSUE TITLE
Questions regarding the code for Metropolis-adjusted Langevin

### ISSUE THREAD

**Issue by Wenlin-Chen** [alisiahkoohi/Langevin-dynamics#3]
Hi, thanks for the repo! I have three questions regarding the code for Metropolis-adjusted Langevin:

1. When a proposal is rejected, why is the gradient not reset (i.e., `self.grad[1].data = self.grad[0].data`)? 
https://github.com/alisiahkoohi/Langevin-dynamics/blob/495de3a6004c07fef1f9b1c3922451f97854736d/langevin_sampling/samplers.py#L212-L214

2. When computing the density of the proposal distribution, why is`P[1]` used for both directions? Shouldn't it be `P[idx^1]`?
https://github.com/alisiahkoohi/Langevin-dynamics/blob/495de3a6004c07fef1f9b1c3922451f97854736d/langevin_sampling/samplers.py#L228-L233

3. Why are the rejected samples discarded? Shouldn't MH keep both accepted and rejected samples in the list?
https://github.com/alisiahkoohi/Langevin-dynamics/blob/495de3a6004c07fef1f9b1c3922451f97854736d/langevin_sampling/samplers.py#L198

**Comment by alisiahkoohi** [comment]
1. `grad[0]` represents the gradient in the last accepted sample, and the gradient in the unaccepted sample is not required anymore.
2. What is meant by "direction"? `P[1]` (preconditioner) acts as the (squared) covariance of the additive noise distribution at the proposed sample and needed for computing the acceptance ratio.
3. The rejected samples themselves are not needed but the duplicates of the accepted samples per rejection might be saved. Feel free to submit a pull request with pointers to references in the comments.
